output "academy_iam_guardrail" {
  description = "True when Academy IAM guardrail checks are present and active"
  value       = true
}

output "forbidden_service_guardrail" {
  description = "True when forbidden service guardrail checks are present and active"
  value       = true
}

output "route53_hosted_zone_id" {
  description = "Route53 hosted zone ID for the base domain"
  value       = aws_route53_zone.primary.zone_id
}

output "route53_hosted_zone_name" {
  description = "Route53 hosted zone DNS name for delegation"
  value       = aws_route53_zone.primary.name
}

output "route53_hosted_zone_name_servers" {
  description = "Authoritative Route53 name servers to set at DotTech"
  value       = aws_route53_zone.primary.name_servers
}

output "dns_apex_record_target_eip" {
  description = "Elastic IP target used by apex DNS A record"
  value       = var.frontend_elastic_ip
}

output "dns_wildcard_record_target_eip" {
  description = "Elastic IP target used by wildcard DNS A record"
  value       = var.frontend_elastic_ip
}

output "dns_api_alias_target_name" {
  description = "API Gateway alias target DNS name for api.matchcota.tech"
  value       = local.api_alias_dns_name
}

output "dns_api_alias_target_zone_id" {
  description = "API Gateway alias target hosted zone ID for api.matchcota.tech"
  value       = local.api_alias_zone_id
}

output "dns_api_custom_domain_name" {
  description = "Configured API custom domain name"
  value       = var.api_custom_domain_name
}

output "api_custom_domain_bootstrap_enabled" {
  description = "True when Terraform owns API custom domain + ACM DNS validation + alias target derivation"
  value       = var.api_custom_domain_bootstrap_enabled
}

output "api_custom_domain_target_domain_name" {
  description = "Regional API Gateway target domain generated by aws_apigatewayv2_domain_name"
  value       = local.use_api_bootstrap_resources ? aws_apigatewayv2_domain_name.api_custom_domain[0].domain_name_configuration[0].target_domain_name : null
}

output "api_custom_domain_target_hosted_zone_id" {
  description = "Hosted zone ID for API custom domain alias target"
  value       = local.use_api_bootstrap_resources ? aws_apigatewayv2_domain_name.api_custom_domain[0].domain_name_configuration[0].hosted_zone_id : null
}

output "api_custom_domain_certificate_arn" {
  description = "Validated ACM certificate ARN bound to the API custom domain"
  value       = local.use_api_bootstrap_resources ? aws_acm_certificate_validation.api_custom_domain[0].certificate_arn : aws_acm_certificate.api_custom_domain.arn
}

output "api_custom_domain_api_mapping_enabled" {
  description = "True when default API mapping resource is managed by Terraform"
  value       = local.should_create_api_mapping
}

output "api_custom_domain_api_mapping_id" {
  description = "API mapping ID when api_gateway_http_api_id is supplied"
  value       = local.use_runtime_api_mapping ? aws_apigatewayv2_api_mapping.api_default[0].id : (local.use_external_api_mapping ? aws_apigatewayv2_api_mapping.api_default_external[0].id : null)
}

output "lambda_function_name" {
  description = "Lambda function name backing api.matchcota.tech runtime"
  value       = aws_lambda_function.runtime.function_name
}

output "lambda_function_arn" {
  description = "Lambda function ARN backing api.matchcota.tech runtime"
  value       = aws_lambda_function.runtime.arn
}

output "lambda_artifact_bucket_name" {
  description = "S3 bucket storing the runtime Lambda artifact"
  value       = aws_s3_object.lambda_runtime_artifact.bucket
}

output "lambda_artifact_object_key" {
  description = "S3 object key storing the runtime Lambda artifact"
  value       = aws_s3_object.lambda_runtime_artifact.key
}

output "api_gateway_http_api_id" {
  description = "HTTP API ID fronting Lambda runtime"
  value       = aws_apigatewayv2_api.runtime.id
}

output "api_gateway_stage_name" {
  description = "HTTP API stage name used for runtime and custom-domain mapping"
  value       = aws_apigatewayv2_stage.runtime_default.name
}

output "api_gateway_invoke_url" {
  description = "HTTP API invoke URL for runtime smoke checks"
  value       = aws_apigatewayv2_stage.runtime_default.invoke_url
}

output "api_custom_domain_runtime_mapping_enabled" {
  description = "True when runtime HTTP API is mapped to the Terraform-managed API custom domain"
  value       = local.use_runtime_api_mapping
}

output "api_acm_validation_record_fqdns" {
  description = "Route53 validation records used for API ACM certificate issuance"
  value       = [for record in aws_route53_record.api_acm_validation : record.fqdn]
}

output "edge_tls_bootstrap_enabled" {
  description = "True when edge TLS bootstrap contract is enabled"
  value       = var.edge_tls_bootstrap_enabled
}

output "edge_tls_bootstrap_user_data" {
  description = "Cloud-init compatible nginx+certbot bootstrap script for apex and wildcard TLS"
  value       = var.edge_tls_bootstrap_enabled ? local.edge_tls_bootstrap_cloud_init : null
  sensitive   = true
}

output "edge_tls_bootstrap_contract" {
  description = "Operational contract for EC2 edge TLS bootstrap and lifecycle ownership"
  value       = var.edge_tls_bootstrap_enabled ? terraform_data.edge_tls_bootstrap_contract[0].input : null
}

output "vpc_id" {
  description = "Production VPC ID consumed by runtime resources"
  value       = aws_vpc.data_plane.id
}

output "public_subnet_ids" {
  description = "Public subnet IDs used by internet-facing resources"
  value = [
    for subnet_name, subnet in local.subnet_layout : aws_subnet.data_plane[subnet_name].id
    if subnet.tier == "public"
  ]
}

output "private_subnet_ids" {
  description = "Private subnet IDs used by data-plane and Lambda runtime resources"
  value = [
    for subnet_name, subnet in local.subnet_layout : aws_subnet.data_plane[subnet_name].id
    if subnet.tier == "private"
  ]
}

output "lambda_runtime_security_group_id" {
  description = "Lambda runtime security group ID for private data-plane access"
  value       = aws_security_group.lambda_runtime.id
}

output "rds_security_group_id" {
  description = "RDS PostgreSQL security group ID with Lambda-only ingress"
  value       = aws_security_group.rds_postgres.id
}

output "rds_endpoint" {
  description = "RDS PostgreSQL endpoint address for runtime database connectivity"
  value       = aws_db_instance.postgres.address
}

output "rds_port" {
  description = "RDS PostgreSQL listener port for runtime database connectivity"
  value       = aws_db_instance.postgres.port
}

output "db_name" {
  description = "RDS database name used by runtime DATABASE_URL construction"
  value       = var.db_name
}

output "db_username" {
  description = "RDS username used by runtime DATABASE_URL construction"
  value       = var.db_username
}

output "uploads_bucket_name" {
  description = "Private uploads bucket name used by runtime object storage"
  value       = aws_s3_bucket.uploads.bucket
}

output "uploads_bucket_arn" {
  description = "Private uploads bucket ARN used by runtime IAM/policy bindings"
  value       = aws_s3_bucket.uploads.arn
}

output "s3_gateway_endpoint_id" {
  description = "S3 gateway endpoint ID attached to private route tables"
  value       = aws_vpc_endpoint.s3_gateway.id
}
