"""add maintenance_level to animals

Revision ID: fafb12bebcd4
Revises: 53b90f4a258a
Create Date: 2026-03-19 16:04:49.309769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafb12bebcd4'
down_revision: Union[str, None] = '53b90f4a258a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('maintenance_level', sa.Numeric(precision=3, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'maintenance_level')
    # ### end Alembic commands ###
